/* Base de Datos Equipos*/

db.Equipos_2020.insertMany ([
    { _id: 1, Equipos:"Mercedes-AMG Petronas Motosport",
    Monoplaza: "Mercedes W11 F1 2020",  
    Año_debut: new Date("1954-07-04"),
    Nº_pilotos:2,
    Nº_empleados_fabrica:860,
    Nº_mecanicos:42},
    { _id: 2, Equipos:"Scuderia Ferrari",
    Monoplaza: "Ferrari SF1000",  
    Año_debut: new Date("1950-05-21"),
    Nº_pilotos:2,
    Nº_empleados_fabrica:960,
    Nº_mecanicos:60},
    { _id: 3, Equipos:"Red Bull Racing",
    Monoplaza: "Red Bull RB16",  
    Año_debut: new Date("2005-03-06"),
    Nº_pilotos:2,
    Nº_empleados_fabrica:740,
    Nº_mecanicos:55},
    { _id: 4, Equipos:"McLaren",
    Monoplaza: "McLaren MCL35",  
    Año_debut: new Date("1966-05-22"),
    Nº_pilotos:2,
    Nº_empleados_fabrica:690,
    Nº_mecanicos:36},
    { _id: 5, Equipos:"Renault F1 Team",
    Monoplaza: "Renault RS20",  
    Año_debut: new Date("1977-07-16"),
    Nº_pilotos:2,
    Nº_empleados_fabrica:620,
    Nº_mecanicos:40},
    { _id: 6, Equipos:"Racing Point Formula One Team",
    Monoplaza: "Racing Point RP20",  
    Año_debut: new Date("2018-08-24"),
    Nº_pilotos:2,
    Nº_empleados_fabrica:405,
    Nº_mecanicos:38},
    { _id: 7, Equipos:"Scuderia AlphaTauri",
    Monoplaza: "Alpha Tauri AT01",  
    Año_debut: new Date("2006-03-12"),
    Nº_pilotos:2,
    Nº_empleados_fabrica:400,
    Nº_mecanicos:30},
    { _id: 8, Equipos:"Alfa Romeo Racing",
    Monoplaza: "Alfa Romeo C39",  
    Año_debut: new Date("1950-05-13"),
    Nº_pilotos:2,
    Nº_empleados_fabrica:360,
    Nº_mecanicos:29},
    { _id: 9, Equipos:"Haas F1 Team",
    Monoplaza: "Haas VF-20",  
    Año_debut: new Date("2016-03-20"),
    Nº_pilotos:2,
    Nº_empleados_fabrica:225,
    Nº_mecanicos:43},
    { _id: 10, Equipos:"Williams Racing",
    Monoplaza: "Williams FW43",  
    Año_debut: new Date("1977-05-08"),
    Nº_pilotos:2,
    Nº_empleados_fabrica:575,
    Nº_mecanicos:45},
])
